class MamanBooksError(Exception): ...
class DownloadError(MamanBooksError): ...
class AllMirrorsFailedError(DownloadError): ...
class FileTooLargeError(DownloadError): ...
class SsrfBlockedError(MamanBooksError): ...
class ConversionError(MamanBooksError): ...
class MailError(MamanBooksError): ...
class VirusTotalError(MamanBooksError): ...
